version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Jmsq0807!
      MYSQL_DATABASE: test_database
      MYSQL_USER: sj
      MYSQL_PASSWORD: 0202
    ports:
      - "3306:3306"  # MySQL 포트 매핑
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
